name: food_recognizer
description: "Submission Dicoding: Belajar Penerapan Machine Learning pada Flutter"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  camera: ^0.11.2
  cupertino_icons: ^1.0.8
  dotted_border: ^3.1.0
  firebase_ai: ^3.3.0
  firebase_core: ^4.1.1
  firebase_ml_model_downloader: ^0.4.0+2
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.1
  google_fonts: ^6.3.2
  http: ^1.5.0
  image: ^4.5.4
  image_cropper: ^11.0.0
  image_picker: ^1.2.0
  provider: ^6.1.5+1
  tflite_flutter: ^0.11.0
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
